// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string event_attempts = "CgkIqLmmnIYUEAIQBw"; // <GPGSID>
        public const string achievement_first_try = "CgkIqLmmnIYUEAIQCw"; // <GPGSID>
        public const string leaderboard_remember_the_darkness = "CgkIqLmmnIYUEAIQDQ"; // <GPGSID>
        public const string event_falls = "CgkIqLmmnIYUEAIQBA"; // <GPGSID>
        public const string leaderboard_classic_wood = "CgkIqLmmnIYUEAIQAQ"; // <GPGSID>
        public const string achievement_level_5 = "CgkIqLmmnIYUEAIQEg"; // <GPGSID>
        public const string event_play_time = "CgkIqLmmnIYUEAIQCA"; // <GPGSID>
        public const string achievement_succesfully_tinkered = "CgkIqLmmnIYUEAIQDw"; // <GPGSID>
        public const string achievement_not_lost = "CgkIqLmmnIYUEAIQEA"; // <GPGSID>
        public const string leaderboard_cardboard_tinkering = "CgkIqLmmnIYUEAIQDA"; // <GPGSID>
        public const string achievement_that_was_easy = "CgkIqLmmnIYUEAIQDg"; // <GPGSID>
        public const string event_collected_stars = "CgkIqLmmnIYUEAIQBg"; // <GPGSID>
        public const string achievement_go_get_some_sun = "CgkIqLmmnIYUEAIQEQ"; // <GPGSID>
        public const string achievement_press_play_to_start = "CgkIqLmmnIYUEAIQCg"; // <GPGSID>
        public const string leaderboard_lost_in_the_middle = "CgkIqLmmnIYUEAIQAw"; // <GPGSID>
        public const string event_completed_levels = "CgkIqLmmnIYUEAIQBQ"; // <GPGSID>

}

